plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true   
header_pages:
  - where-ive-worked.md
  - case-studies/index.md
  - contact.md  
theme: minima
